### ISSUE TITLE
"Aspecto do relevo" para Orientação da encosta?

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [Resiliencia-climatica-Brasil/workshop#14]
Só me perguntando aqui se a gente mantém o anglicismo https://github.com/Resiliencia-climatica-Brasil/workshop/blob/773c848106a61a46ba8a3a13b4cd9a760161613c/implementacao.qmd#L96
Marquei Luciano mas qualquer um pode opinar.

**Comment by queridolca** [comment]
Concordo em trocar para orientação da encosta! fica melhor! Eu tinha só traduzido mesmo, não tinha pensado nisso
